CREATE OR REPLACE VIEW MI181_PCRAGSAC.VIEW_VIEW
(HOT_NAME,BILL_DMG,ID)
AS
SELECT MI181_PCRAGSAC.bill.HOT_NAME,
    MI181_PCRAGSAC.bill.BILL_DMG,
    MI181_PCRAGSAC.hotel.id
   FROM (MI181_PCRAGSAC.bill
     LEFT JOIN MI181_PCRAGSAC.hotel ON ((MI181_PCRAGSAC.bill.id = MI181_PCRAGSAC.hotel.id)));
	 

  CREATE OR REPLACE FORCE VIEW "MI181_PCRAGSAC"."CUSTOMER_ROOM_VIEW" ("CUS_FNAME", "CUS_LNAME", "ID") AS 
  SELECT MI181_PCRAGSAC.customer.cus_fname,
    MI181_PCRAGSAC.customer.cus_lname,
    MI181_PCRAGSAC.room.id
   FROM (MI181_PCRAGSAC.customer
     LEFT JOIN MI181_PCRAGSAC.room ON ((MI181_PCRAGSAC.CUSTOMER.id = MI181_PCRAGSAC.room.id)));